### ISSUE TITLE
Problem if there is 'url_suffix' in the config

### ISSUE THREAD

**Issue by orangevinz** [jackboberg/CodeIgniter-Assets#3]
Hi,

Thanks for your lib, I'm just trying now but it seems to be the one ;-)

In my CI config file I got an "url_suffix" which is '.html'
and the link generated is like ".css.html" so I've just modified the line 737 (assets library file) to fix that.

-- $url = site_url($dir . $path);
++ $url = base_url($dir . $path);

Hope that helps

Vinz

**Comment by jackboberg** [comment]
updated library, thanks
